### ISSUE TITLE
data-bhs schema

### ISSUE THREAD

**Issue by TahorSuiJuris** [parabible/data-module-bhsa#1]
Would really love to view schema, er diagram.
data-bhs
Build the BHS data needed for parabible's backend

**Comment by jcuenod** [comment]
Hey Tahor,

I'm in the process of building this for an improved backend (which I have not yet pushed) that is a little more intuitive for developers who want to contribute something. I am in the (slow) process of improving data that originally I just threw together, though. The old enrichments are at https://github.com/jcuenod/tf-accent-data and https://github.com/jcuenod/biblecrawler-lxx-join/, for example.

It's a much larger project now though because I am going to import both versions of the LXX and, hopefully, provide room to import the DSS and texts like the Apostolic Fathers. I'm hoping that these moves will make the backend more flexible and able to do more advanced types of searches but it needs a fair bit of work and although I'd hoped to be done by the end of the summer, more and more it's looking like this will only be complete some time next year.

The point is that the schema is in flux right now so if I uploaded what it is it would change and if I uploaded what it will be (which could still change) it will not be true for some time.

**Comment by jcuenod** [comment]
Hey @TahorSuiJuris,
I just stumbled across this issue again. It's obviously been a long time and I'm still not done with all this work but I'm much further along. The main thing I wanted to point you to is this: https://github.com/jcuenod/parabible-data-pipeline/tree/master/hb-bhs-pipe

If you clone that folder (e.g. with degit) `degit jcuenod/parabible-data-pipeline/hb-bhs-pipe`, you will be able to build the BHS data that parabible's backend is going to be using when I do a major upgrade. I haven't finished getting all the "enrichments" currently available (e.g. accent data, semantic domains, lxx lexemes) into this pipeline but it's a major step in that direction.

**Comment by jcuenod** [comment]
@TahorSuiJuris I've just pushed an update. Parabible's data pipeline will use https://github.com/parabible/data-compiler/. This is one of the modules. The link I sent you previously still houses a number of the modules that I haven't broken out yet. So again, still work to do, but it's coming along :)
